name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        REACT_APP_GITHUB_URL: ${{ secrets.REACT_APP_GITHUB_URL }}
        REACT_APP_GITHUB_TOKEN: ${{ secrets.REACT_APP_GITHUB_TOKEN }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        token: ${{ secrets.REACT_APP_GITHUB_TOKEN }}
        branch: gh-pages
        folder: build
